### ISSUE TITLE
Reason for going from Apache 2 license to Unlicense?

### ISSUE THREAD

**Issue by paazmaya** [inexorabletash/text-encoding#57]
I am just curious, what was the reason to make https://github.com/inexorabletash/text-encoding/commit/630eed16d5a89958f9ab279059d0c8b0960d5a51 happen?

I was about to request changing to MIT license from Unlicense, but instead opened this question...

**Comment by inexorabletash** [comment]
Since my main goal for the polyfill is to be a reference implementation for the Encoding standard (i.e. helps find bugs in the specified algoritihms), I wanted it to have as unrestrictive a license as possible, like the spec. (Someone also wanted to pull it into a CDN and the license tags was slightly off which prompted me to revisit which license was used, but I was planning to pick a new software license as close to CC0 as possible.)

**Comment by paazmaya** [comment]
Thank you for the clarification.

**Comment by ilatypov** [comment]
The no-warranty clause contradicts the no-ownership clause, according to Rick Moen.  https://lists.opensource.org/pipermail/license-review/2012-January/001386.html

I wonder if this may get enterprise lawyers defensive when their employer adopts this package directly and via requisite dependencies?
