### ISSUE TITLE
Problem with encoding SJIS text

### ISSUE THREAD

**Issue by aleris** [inexorabletash/text-encoding#71]
I am having problems encoding Shift_JIS text, If I try to encode a character (in my case "点"), instead of getting 2 bytes I get 3 incorrect bytes. Decoding seems to work ok. Am I missing something?

Test code:
```javascript
const textEncoder = new TextEncoder("Shift_JIS")
const textDecoder = new TextDecoder("Shift_JIS")

const text = "点"

console.log("Decode from bytes:")
const bytes = Uint8Array.from([0x93,0x5f])
const textResultFromBytes = textDecoder.decode(bytes)
console.log(bytes, "->", textResultFromBytes, textResultFromBytes === text ? "OK": "NOT OK")

console.log("Encode text then decode again:")
const bytesOfText = textEncoder.encode(text)
const textResultFromText = textDecoder.decode(bytesOfText)
console.log(text, "->", bytesOfText, "->", textResultFromText, textResultFromText === text ? "OK": "NOT OK")

````

Console output:
```
Decode from bytes:
Uint8Array(2) [147, 95] "->" "点" "OK"
Encode text then decode again:
点 -> Uint8Array(3) [231, 130, 185] -> 轤ｹ NOT OK
```

This quick test is also available here:
https://jsfiddle.net/aleris/pt17dkz3/

**Comment by inexorabletash** [comment]
By default, the code acts as a polyfill for the API in [Encoding](https://encoding.spec.whatwg.org) which does not offer encoding to anything but UTF-8. So it's possible one of two things is happening:

* You're getting the browser's native TextEncoder rather than the polyfill.
* You're getting the polyfill's TextEncoder, but not passing the ` { NONSTANDARD_allowLegacyEncoding: true }` option in.

**Comment by aleris** [comment]
👍
So I was missing something from the docs.
Seems to work with { NONSTANDARD_allowLegacyEncoding: true } in nodejs. I will have to test it in browsers also.
Thanks.

**Comment by inexorabletash** [comment]
Cool, glad you got that figured out.
